#!/usr/bin/env bash
# This script displays DNS information about a domain and its subdomains

domain=$1
subdomain=$2

get_record() {
    result=$(dig "$1.$domain" +noall +answer)
    record_type=$(echo "$result" | awk '{print $4}')
    destination=$(echo "$result" | awk '{print $5}')

    echo "The subdomain $1 is a $record_type record and points to $destination"
}

if [ -z "$subdomain" ]; then
    get_record www
    get_record lb-01
    get_record web-01
    get_record web-02
else
    get_record "$subdomain"
fi

